# Generated by Django 2.1 on 2018-10-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
