# Generated by Django 2.1 on 2018-12-12 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content_link', models.CharField(max_length=500)),
                ('thumbnail_link', models.CharField(max_length=500)),
                ('published_on', models.DateTimeField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Publishing_Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('abbreviation', models.CharField(default=None, max_length=10)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('geo_id', models.CharField(max_length=500, null=True)),
                ('state_number', models.IntegerField(null=True)),
                ('census_area', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Region_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.Region')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='region_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.Region_Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='publishing_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.Publishing_Organization'),
        ),
    ]
