# Generated by Django 2.1 on 2018-12-27 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_init_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStaging',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content_link', models.CharField(max_length=500)),
                ('thumbnail_link', models.CharField(max_length=500)),
                ('published_on', models.DateTimeField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('publishing_organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='news_app.Publishing_Organization')),
            ],
        ),
    ]
