# Generated by Django 2.1 on 2018-10-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_auto_20181021_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='census_area',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='geo_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='state_number',
            field=models.IntegerField(null=True),
        ),
    ]
