# Generated by Django 2.1 on 2018-11-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_auto_20181021_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content_link', models.CharField(max_length=500)),
                ('thumbnail_link', models.CharField(max_length=500)),
                ('published_on', models.DateTimeField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PublishingOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='publishing_organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.PublishingOrganization'),
        ),
    ]
