# Generated by Django 2.1 on 2018-11-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_auto_20181120_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishingorganization',
            name='abbreviation',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
