# Generated by Django 2.1 on 2018-11-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_auto_20181120_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publishing_organization_id',
            new_name='publishing_organization',
        ),
    ]
