# Generated by Django 2.1 on 2018-11-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_auto_20181120_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublishingOrganization',
            new_name='Publishing_Organization',
        ),
        migrations.RenameModel(
            old_name='RegionCategory',
            new_name='Region_Category',
        ),
        migrations.RenameModel(
            old_name='UserQuery',
            new_name='User_Query',
        ),
    ]
